from random import sample

class Preguntas:
    """
    Posibles preguntas para los examenes de certificacion de Snowflake
    1.- SnowPro Core
    
    """
    
    def __init__(self, num_preguntas:int):
        """
            Metodo que se encarga de inicializar el cuestionario por tema

        Args:
            tema (string): Tema requerido para generar las preguntas. 
        """
        
        if not isinstance(num_preguntas, (int)) or num_preguntas <= 0:
            raise ValueError("El número de preguntas debe de ser mayor a 0")
        self.num_preguntas = num_preguntas
        
        
    def arquitectura(self):
        
        quiz = [ { "question": "What enables Snowflake to support massive concurrency without data contention?", "type": "multiple_choice", "answers": [ {"answer": "Data is replicated across all warehouses for parallel reads", "correct": False}, {"answer": "Warehouses share a distributed file system cache", "correct": False}, {"answer": "Compute is fully isolated while all nodes access the same centralized storage", "correct": True}, {"answer": "Data is copied to each cluster on demand", "correct": False} ] }, { "question": "Which Snowflake layer manages metadata, optimization, and authentication?", "type": "multiple_choice", "answers": [ {"answer": "Storage Layer", "correct": False}, {"answer": "Cloud Services Layer", "correct": True}, {"answer": "Virtual Warehouse Layer", "correct": False}, {"answer": "Compute Layer", "correct": False} ] }, { "question": "A Resource Monitor is set to Suspend Immediately at 90% of credits. What happens when the threshold is hit?", "type": "multiple_choice", "answers": [ {"answer": "Queries continue but run at reduced speed", "correct": False}, {"answer": "Warehouses scale down to minimum size automatically", "correct": False}, {"answer": "Credits reset and queries restart", "correct": False}, {"answer": "Assigned warehouses are suspended and cannot resume until reset or quota increased", "correct": True} ] }, { "question": "What differentiates manual clustering from automatic clustering?", "type": "multiple_choice", "answers": [ {"answer": "Manual clustering uses cloud services; automatic uses warehouses", "correct": False}, {"answer": "Automatic clustering is cheaper", "correct": False}, {"answer": "Automatic clustering requires explicit reclustering commands", "correct": False}, {"answer": "Manual clustering uses warehouse compute; automatic clustering is fully managed by Snowflake", "correct": True} ] }, { "question": "When might manual clustering be preferred?", "type": "multiple_choice", "answers": [ {"answer": "When Snowflake disallows clustering keys", "correct": False}, {"answer": "When no background services are available", "correct": False}, {"answer": "When precise cost control over reclustering is needed", "correct": True}, {"answer": "When table size is under 1 GB", "correct": False} ] }, { "question": "Why do different virtual warehouses NOT share cache?", "type": "multiple_choice", "answers": [ {"answer": "Because Snowflake uses customer-provided SSDs", "correct": False}, {"answer": "To ensure compute isolation and predictable performance", "correct": True}, {"answer": "Because caching is stored in user schemas", "correct": False}, {"answer": "Because storage is ephemeral", "correct": False} ] }, { "question": "Which is the correct fully-qualified object naming sequence?", "type": "multiple_choice", "answers": [ {"answer": "<database>.<schema>.<object>", "correct": True}, {"answer": "<schema>.<table>.<column>", "correct": False}, {"answer": "<object>.<schema>.<database>", "correct": False}, {"answer": "<warehouse>.<database>.<object>", "correct": False} ] }, { "question": "How do schema-level privileges help reduce blast radius?", "type": "multiple_choice", "answers": [ {"answer": "They prevent Time Travel access", "correct": False}, {"answer": "They allow cross-database joins", "correct": False}, {"answer": "They encrypt all objects by default", "correct": False}, {"answer": "They limit privileges to specific namespaces without affecting others", "correct": True} ] }, { "question": "Which table type includes Fail-safe?", "type": "multiple_choice", "answers": [ {"answer": "Temporary", "correct": False}, {"answer": "Transient", "correct": False}, {"answer": "External", "correct": False}, {"answer": "Permanent ", "correct": True} ] }, { "question": "Why are temporary tables cost-efficient for ETL?", "type": "multiple_choice", "answers": [ {"answer": "They auto-compress all data", "correct": False}, {"answer": "They replicate across regions", "correct": False}, {"answer": "They have no Fail-safe and auto-drop at session end", "correct": True}, {"answer": "They cannot be cloned", "correct": False} ] }, { "question": "What happens when cloning a transient table?", "type": "multiple_choice", "answers": [ {"answer": "Clone gains Fail-safe protection", "correct": False}, {"answer": "Fail-safe window is extended", "correct": False}, {"answer": "Clone is automatically permanent", "correct": False}, {"answer": "Clone inherits no Fail-safe and only current Time Travel history", "correct": True} ] }, { "question": "A permanent table with 1-day Time Travel is dropped. How long is the table recoverable?", "type": "multiple_choice", "answers": [ {"answer": "1 day only", "correct": False}, {"answer": "7 days only", "correct": False}, {"answer": "1 day Time Travel + 7 days Fail-safe", "correct": True}, {"answer": "Indefinitely", "correct": False} ] }, { "question": "Why can only Snowflake perform Fail-safe recovery?", "type": "multiple_choice", "answers": [ {"answer": "It uses internal metadata and immutable storage snapshots", "correct": True}, {"answer": "Fail-safe uses customer-managed keys", "correct": False}, {"answer": "It is stored in the Virtual Warehouse layer", "correct": False}, {"answer": "It requires manual SQL commands", "correct": False} ] }, { "question": "Does increasing Time Travel retention affect query performance?", "type": "multiple_choice", "answers": [ {"answer": "Yes, because partitions are recomputed", "correct": False}, {"answer": "Yes, because warehouses must keep data cached", "correct": False}, {"answer": "No, only storage cost increases", "correct": True}, {"answer": "No, because older data is purged immediately", "correct": False} ] }, { "question": "What makes Secure Views secure?", "type": "multiple_choice", "answers": [ {"answer": "They must use Materialized Views as the source", "correct": False}, {"answer": "They encrypt the result set in the table", "correct": False}, {"answer": "They disable Time Travel", "correct": False}, {"answer": "They hide underlying SQL and prevent metadata exposure", "correct": True} ] }, { "question": "Why do Materialized Views increase storage cost?", "type": "multiple_choice", "answers": [ {"answer": "They store multiple copies of the base table", "correct": False}, {"answer": "They store pre-computed micro-partitions on disk", "correct": True}, {"answer": "They replicate data across warehouses", "correct": False}, {"answer": "They require continuous warehouse execution", "correct": False} ] }, { "question": "Which view type is best for fast dashboard queries over stable datasets?", "type": "multiple_choice", "answers": [ {"answer": "Secure View", "correct": False}, {"answer": "Non-Materialized View", "correct": False}, {"answer": "Materialized View", "correct": True}, {"answer": "Temporary View", "correct": False} ] }, { "question": "Which of the following is not allowed in a Materialized View?", "type": "multiple_choice", "answers": [ {"answer": "Aggregations", "correct": False}, {"answer": "Deterministic functions", "correct": False}, {"answer": "Wildcard SELECT (SELECT *)", "correct": True}, {"answer": "Filters", "correct": False} ] }, { "question": "Can you create a Materialized View on top of another Materialized View?", "type": "multiple_choice", "answers": [ {"answer": "No, chaining Materialized Views is not allowed", "correct": True}, {"answer": "Yes, but only in Enterprise edition", "correct": False}, {"answer": "Yes, but only if clustering keys match", "correct": False}, {"answer": "No, but you can chain Secure Views", "correct": False} ] }, { "question": "What is a trade‑off when using Secure Views?", "type": "multiple_choice", "answers": [ {"answer": "They cannot reference permanent tables", "correct": False}, {"answer": "They cost credits to maintain", "correct": False}, {"answer": "They lose Time Travel capability", "correct": False}, {"answer": "Certain performance optimizations (like predicate pushdown) may be restricted", "correct": True} ] } ]
        
        if self.num_preguntas > len(quiz):
            raise ValueError("El número de preguntas solicitado es mayor que las disponibles en el cuestionario.")
        
        return sample(quiz, self.num_preguntas)
    
    def uno(self):
        
        quiz = [ { "question": "Data Consumers can be set up to consume data using which two types of consuming accounts?", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "Sharing Accounts & Query Accounts", 
                        "correct": False}, 
                       {"answer": "Full Accounts & Reader Accounts", 
                        "correct": True}, 
                       {"answer": "Sharing Accounts & Providing Accounts", 
                        "correct": False}, 
                       {"answer": "Query Accounts & Full Accounts", 
                        "correct": False} ]},
                { "question": "Snowflake is what kind of offering?", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "On Premise Application", 
                        "correct": False}, 
                       {"answer": "Software as a service (SaaS)", 
                        "correct": True}, 
                       {"answer": "Platform as a service (PaaS)", 
                        "correct": False}, 
                       {"answer": "Infrastructure as a service (IaaS)", 
                        "correct": False} ] },
                { "question": "Which of the below two stages are automatically created and need not be configured explicitly by the user:", 
                   "type": "many_choice", 
                   "answers": [ 
                       {"answer": "User Stage", 
                        "correct": True}, 
                       {"answer": "Role Stage", 
                        "correct": False}, 
                       {"answer": "S3 Stage", 
                        "correct": False}, 
                       {"answer": "Internal Stage", 
                        "correct": False},
                       {"answer": "Table Stage", 
                        "correct": True}, 
                       {"answer": "External Stage", 
                        "correct": False} ] },
                { "question": "What is the recommended file size, to optimize the number of parallel operation for a load?", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "50 MB to 150 MB (Compressed)", 
                        "correct": False}, 
                       {"answer": "100-250 MB (Compressed)", 
                        "correct": True}, 
                       {"answer": "1 MB to 10 MB (Compressed)", 
                        "correct": False}, 
                       {"answer": "None of the above", 
                        "correct": False} ] },
                { "question": "Snowflake Instances in different regions require separate accounts...", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "False", 
                        "correct": False}, 
                       {"answer": "True", 
                        "correct": True} ] }, 
                { "question": "Shares take place between which two groups?", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "Sharers & Consumers", 
                        "correct": False}, 
                       {"answer": "Providers & Consumers", 
                        "correct": True}, 
                       {"answer": "Data Writers & Data Readers", 
                        "correct": False}, 
                       {"answer": "Full Accounts & Reading Accounts", 
                        "correct": False} ] }, 
                { "question": "Mark the types of Stages available in Snowflake:", 
                   "type": "many_choice", 
                   "answers": [ 
                       {"answer": "User Stage", 
                        "correct": True}, 
                       {"answer": "Role Stage", 
                        "correct": False}, 
                       {"answer": "S3 Stage", 
                        "correct": False}, 
                       {"answer": "Internal Stage", 
                        "correct": True},
                       {"answer": "Table Stage", 
                        "correct": True}, 
                       {"answer": "External Stage", 
                        "correct": True} ] },
                { "question": "Which command is used to download the data from Snowflake Stage?", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "DOWNLOAD", 
                        "correct": False}, 
                       {"answer": "PUT", 
                        "correct": False}, 
                       {"answer": "GET", 
                        "correct": True}, 
                       {"answer": "RETRIEVE", 
                        "correct": False} ] },
                { "question": "If you find a data-related tool that is not listed as part of the Snowflake ecosystem, what industry standard options could you check for as a way to easily connect to Snowflake?", 
                   "type": "many_choice", 
                   "answers": [ 
                       {"answer": "Check to see if the tool can connect to other solutions via ODBC", 
                        "correct": True}, 
                       {"answer": "Check to see if the tool can connect to other solutions via JDBC", 
                        "correct": True}, 
                       {"answer": "Check to see if you can develop a driver and put it on Github", 
                        "correct": False}, 
                       {"answer": "Check to see if there is a petition in the community to create a driver", 
                        "correct": False} ] },
                { "question": "External Stages require a cloud storage provider...", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "False", 
                        "correct": False}, 
                       {"answer": "True", 
                        "correct": True} ] },
                { "question": "A CAST command will force a value to be output as a certain datatype. Which of the following symbols will result in the “castcolumn“ being output using the VARCHAR datatype?", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "SELECT VARCHAR(castcolumn)", 
                        "correct": False}, 
                       {"answer": "SELECT castcolumn as VARCHAR", 
                        "correct": False}, 
                       {"answer": "SELECT castcolumn||VARCHAR", 
                        "correct": False}, 
                       {"answer": "SELECT castcolumn::VARCHAR", 
                        "correct": True} ] },
                { "question": "Which SQL statements can work on a cloned Table?", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "SELECT command", 
                        "correct": False}, 
                       {"answer": "SHOW command", 
                        "correct": False}, 
                       {"answer": "DROP table command", 
                        "correct": False}, 
                       {"answer": "All of the above", 
                        "correct": True} ] },
                { "question": "Which of the following Snowflake Editions provides automatic encryption of all data?", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "All Editions provide automatic encryption of all data", 
                        "correct": True}, 
                       {"answer": "Standard", 
                        "correct": False}, 
                       {"answer": "Business Critical", 
                        "correct": False}, 
                       {"answer": "Enterprise", 
                        "correct": False} ] },
                { "question": "Scaling in is a manual process (e.g. Max Clusters to min clusters)...", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "False", 
                        "correct": True}, 
                       {"answer": "True", 
                        "correct": False} ] },
                { "question": "Snowflake Administrators should utilize resource monitors to help control costs and avoid unexpected credit usage. Which of the following actions can Snowflake's resource monitor triggers initiate automatically? (Check all that apply)", 
                   "type": "many_choice", 
                   "answers": [ 
                       {"answer": "Roll over query executions to under utilized warehouses", 
                        "correct": False}, 
                       {"answer": "Impose limits on the number of credits that warehouses consume each month", 
                        "correct": True}, 
                       {"answer": "Trigger alert notifications for high usage", 
                        "correct": True}, 
                       {"answer": "Trigger warehouse suspension for high usager", 
                        "correct": True} ] },
                { "question": "Which of the following are Snowflake view types?", 
                   "type": "many_choice", 
                   "answers": [ 
                       {"answer": "External", 
                        "correct": False}, 
                       {"answer": "Permanent", 
                        "correct": False}, 
                       {"answer": "Secure", 
                        "correct": True}, 
                       {"answer": "Materialized", 
                        "correct": True},
                       {"answer": "Standard", 
                        "correct": True},
                       {"answer": "Transient", 
                        "correct": False} ] },
                 { "question": "How many number of shares can be created in a Snowflake Account?", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "10", 
                        "correct": False}, 
                       {"answer": "50", 
                        "correct": False}, 
                       {"answer": "Unlimited", 
                        "correct": True}, 
                       {"answer": "100", 
                        "correct": False} ] },
                 { "question": "How many number of consumer accounts can be added to a single share?", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "10", 
                        "correct": False}, 
                       {"answer": "50", 
                        "correct": False}, 
                       {"answer": "Unlimited", 
                        "correct": True}, 
                       {"answer": "100", 
                        "correct": False} ] },
                 { "question": "When a data is shared with an existing snowflake customer, the compute is charged to?", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "Provider", 
                        "correct": False}, 
                       {"answer": "Consumer", 
                        "correct": True}, 
                       {"answer": "No charges applied", 
                        "correct": False} ] },
                 { "question": "Which of the below is not a role available when Snowflake account is created initially?", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "Accountadmin", 
                        "correct": False}, 
                       {"answer": "Sysadmin", 
                        "correct": False}, 
                       {"answer": "Useradmin", 
                        "correct": False}, 
                       {"answer": "Developer", 
                        "correct": True} ] },
                 { "question": "In the Snowflake container hierarchy, what container is represented as a URL (for example: https://AB12345.snowflakecomputing.com)?", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "Database", 
                        "correct": False}, 
                       {"answer": "Schema", 
                        "correct": False}, 
                       {"answer": "Role", 
                        "correct": False}, 
                       {"answer": "Account", 
                        "correct": True} ] },
                 { "question": "MFA can be used for connecting to Snowflake via the Snowflake JDBC driver...", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "False", 
                        "correct": False}, 
                       {"answer": "True", 
                        "correct": True} ] },
                 { "question": "Which of the following Snowflake Editions automatically store data in an encrypted state?", 
                   "type": "many_choice", 
                   "answers": [ 
                       {"answer": "Standard", 
                        "correct": True}, 
                       {"answer": "Enterprise", 
                        "correct": True}, 
                       {"answer": "Business Critical", 
                        "correct": True} ] },
                 { "question": "What are the names of the three Snowflake Editions offered when signing up for a trial account?", 
                   "type": "many_choice", 
                   "answers": [ 
                       {"answer": "Free-Tier Basic", 
                        "correct": False}, 
                       {"answer": "Ultra", 
                        "correct": False}, 
                       {"answer": "Enterprise", 
                        "correct": True}, 
                       {"answer": "Business Critical", 
                        "correct": True},
                       {"answer": "Standard", 
                        "correct": True} ] },
                 { "question": "Tri-secret requires that customers manage their own keys...", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "False", 
                        "correct": False}, 
                       {"answer": "True", 
                        "correct": True} ] },
                 { "question": "What functional category does Looker fall into?", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "Data Integration", 
                        "correct": False}, 
                       {"answer": "SQL Editors", 
                        "correct": False}, 
                       {"answer": "Business Intelligence", 
                        "correct": True}, 
                       {"answer": "Security & Governance", 
                        "correct": False},
                       {"answer": "Advanced Analytics", 
                        "correct": False},
                       {"answer": "Programmatic Interfaces", 
                        "correct": False}] },
                 { "question": "Which statements about Data Integration Tech Partners are true?", 
                   "type": "many_choice", 
                   "answers": [ 
                       {"answer": "Data Integration Tech Partner software can be used to extract data from other systems.", 
                        "correct": True}, 
                       {"answer": "Data Integration Tech Partner software can be used to carry out transformations.", 
                        "correct": True}, 
                       {"answer": "Snowflake can carry out transformations after loading files staged by partner software (ELT).", 
                        "correct": True}, 
                       {"answer": "Snowflake must be used to extract data from other databases but Data Integration Tech Partner software can load data", 
                        "correct": False},
                       {"answer": "Snowflake can be used to extract data from other databases but Data Integration Tech Partner software must be used to do transformations.", 
                        "correct": False},
                       {"answer": "Data Integration Tech Partner software should be used to deliver data to stages, Snowflake is then used to load the data", 
                        "correct": True} ] },
                 { "question": "Query execution is performed by which layers of Snowflake architecture?", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "Storage Layer", 
                        "correct": False}, 
                       {"answer": "Cloud Services Layer", 
                        "correct": False}, 
                       {"answer": "Query Processing Layer", 
                        "correct": True} ] },
                 { "question": "Snowflake account hosted on AWS cannot load data from a file that is staged on GCP or Azure...", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "False", 
                        "correct": True}, 
                       {"answer": "True", 
                        "correct": False} ] },
                 { "question": "When data is shared with a non-Snowflake customer (via a Reader Account), who is charged for the compute usage?", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "Provider", 
                        "correct": True}, 
                       {"answer": "Consumer", 
                        "correct": False}, 
                       {"answer": "No charges applied", 
                        "correct": False} ] },
                 { "question": "Which file format option should be enabled while loading a JSON file to remove the outer most array structure and load the records in separate table rows?", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "REMOVE_OUTER_ARRAY", 
                        "correct": False}, 
                       {"answer": "ELIMINATE_OUTER_ARRAY", 
                        "correct": False}, 
                       {"answer": "STRIP_OUTER_ARRAY", 
                        "correct": True}, 
                       {"answer": "READ_INNER_ARRAY", 
                        "correct": False} ] },
                 { "question": "To configure an External Stage you need to define the stage object in Snowflake. You also need two additional components. What are they?", 
                   "type": "many_choice", 
                   "answers": [ 
                       {"answer": "Stage Admin Password", 
                        "correct": False}, 
                       {"answer": "Cloud storage location (e.g. S3 Bucket)", 
                        "correct": True}, 
                       {"answer": "Stage Admin Username", 
                        "correct": False}, 
                       {"answer": "Cloud access credentials (e.g. IAM User and Policy)", 
                        "correct": True},
                       {"answer": "Snowflake External Stage Password Authentication Certificate", 
                        "correct": False} ] },
                 { "question": "Out of below four options, which options require a running warehouse when retrieving data from them??", 
                   "type": "many_choice", 
                   "answers": [ 
                       {"answer": "Results Cache", 
                        "correct": False}, 
                       {"answer": "Local Disk Cache", 
                        "correct": True}, 
                       {"answer": "Warehouse Cache", 
                        "correct": True}, 
                       {"answer": "Metadata Cache", 
                        "correct": False} ] },
                 { "question": "Check all true statements about Fail-safe:", 
                   "type": "many_choice", 
                   "answers": [ 
                       {"answer": "The data stored as part of fail-safe is part of storage costs charged to customers", 
                        "correct": True}, 
                       {"answer": "Fail-safe is not available for tables that have Time Travel.", 
                        "correct": False}, 
                       {"answer": "Fail-safe is a reliable way to create Dev/Test/QA and other environments", 
                        "correct": False}, 
                       {"answer": "Only a Snowflake employee can recover data from fail-safe storage", 
                        "correct": True}] },
                 { "question": "With Snowflake, the customer needs to perform hardware maintenance, upgrades or regular patches...", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "False", 
                        "correct": True}, 
                       {"answer": "True", 
                        "correct": False} ] },
                 { "question": "For databases, schemas, and tables, a clone does not contribute to the overall data storage until operations are performed on the clone that modify existing data or add new data...", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "False", 
                        "correct": False}, 
                       {"answer": "True", 
                        "correct": True} ] },
                 { "question": "The Query Profiler view is only available for completed queries....", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "False", 
                        "correct": True}, 
                       {"answer": "True", 
                        "correct": False} ] },
                 { "question": "Which of the below is role is automatically granted to every user and role in the account?", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "Sysadmin", 
                        "correct": False}, 
                       {"answer": "Developer", 
                        "correct": False}, 
                       {"answer": "Public", 
                        "correct": True}, 
                       {"answer": "Useradmin", 
                        "correct": False} ] },
                 { "question": "With Time Travel,  a Snowflake administrator can, analyze data manipulation over specified periods of time...", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "False", 
                        "correct": False}, 
                       {"answer": "True", 
                        "correct": True} ] },
                 { "question": "Scaling up is a manual process. (e.g. Small to Medium)...", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "False", 
                        "correct": False}, 
                       {"answer": "True", 
                        "correct": True} ] },
                 { "question": "Snowflake caches are automatically invalidated if the underlying data changes....", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "False", 
                        "correct": False}, 
                       {"answer": "True", 
                        "correct": True} ] },
                 { "question": "If a table is cloned with COPY GRANTS option specified, then the clone object inherits any explicit access privileges granted on the original table, but does not inherit any future grants defined for the table in the schema...", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "False", 
                        "correct": False}, 
                       {"answer": "True", 
                        "correct": True} ] },
                 { "question": "What is the maximum number of consumer accounts that can be added to a Share object?", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "10", 
                        "correct": False}, 
                       {"answer": "One", 
                        "correct": False}, 
                       {"answer": "Unlimited", 
                        "correct": True}, 
                       {"answer": "100", 
                        "correct": False} ] },
                 { "question": "Data can be shared READ-ONLY across Snowflake accounts and Shared Data can also be cloned...", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "False", 
                        "correct": True}, 
                       {"answer": "True", 
                        "correct": False} ] },
                 { "question": "Snowflake compute costs depend on which of the following?", 
                   "type": "many_choice", 
                   "answers": [ 
                       {"answer": "The number of rows returned in queries.", 
                        "correct": False}, 
                       {"answer": "The total number of warehouses in the account", 
                        "correct": False}, 
                       {"answer": "The amount of time warehouses have run.", 
                        "correct": True}, 
                       {"answer": "The sizes of running warehouses.", 
                        "correct": True} ] },
                 { "question": "What technique does Snowflake use to limit the number of micro-partitions scanned by each query?", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "Indexing", 
                        "correct": False}, 
                       {"answer": "B-Tree", 
                        "correct": False}, 
                       {"answer": "Pruning", 
                        "correct": True}, 
                       {"answer": "Map Reduce", 
                        "correct": False} ] },
                 { "question": "How often does Snowflake release new features?", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "Yearly", 
                        "correct": False}, 
                       {"answer": "Never", 
                        "correct": False}, 
                       {"answer": "Weekly", 
                        "correct": True}, 
                       {"answer": "Monthly", 
                        "correct": False},
                       {"answer": "Bi-Annually", 
                        "correct": False}] },
                 { "question": "Which of the following techniques can be used in Snowflake to improve query performance?", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "Index definition", 
                        "correct": False}, 
                       {"answer": "Distribution keys", 
                        "correct": False}, 
                       {"answer": "Cluster Keys/Reclustering", 
                        "correct": True}, 
                       {"answer": "Query Hints", 
                        "correct": False} ] },
                 { "question": "Data from Fail-Safe can only be accessed / restored by Snowflake Employees?", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "False", 
                        "correct": False}, 
                       {"answer": "True", 
                        "correct": True} ] },
                 { "question": "Cloud storage providers must be linked to internal stage objects...", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "False", 
                        "correct": True,
                        "feedback": "Cloud storage providers must be linked to external stage objects. For internal stage, there is no need to explicitly specify any cloud storage provider like AWS, Azure, GCP."}, 
                       {"answer": "True", 
                        "correct": False,
                        "feedback": "Cloud storage providers must be linked to external stage objects. For internal stage, there is no need to explicitly specify any cloud storage provider like AWS, Azure, GCP."} ] },
                 { "question": "Snowflake Stages can be defined as either External or Internal....", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "False", 
                        "correct": False}, 
                       {"answer": "True", 
                        "correct": True} ] },
                 { "question": "The Cloning feature in Snowflake requires less storage because...", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "The cloned data is constantly updated to synchronize with original table data", 
                        "correct": False}, 
                       {"answer": "PUData is replicated to ensure integrity of data in the original table dataT", 
                        "correct": False}, 
                       {"answer": "Only metadata is copied; no physical data is copied", 
                        "correct": True} ] },
                 { "question": "When data is loaded into Snowflake, Snowflake reorganizes that data into its internal optimized, compressed, columnar format...", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "False", 
                        "correct": False}, 
                       {"answer": "True", 
                        "correct": True} ] },
                 { "question": "Snowflake data warehouse is built on top of Hadoop Big Data Software Platform...", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "False", 
                        "correct": True}, 
                       {"answer": "True", 
                        "correct": False} ] },
                 { "question": "Cloning the table does not include the load history of the source table, and hence the data files that were loaded in source table can be loaded again into its clone tables...", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "False", 
                        "correct": False}, 
                       {"answer": "True", 
                        "correct": True} ] },
                 { "question": "Cloud Services layer of Snowflake provide which all functionalities?", 
                   "type": "many_choice", 
                   "answers": [ 
                       {"answer": "Infra Management", 
                        "correct": True}, 
                       {"answer": "Authentication", 
                        "correct": True}, 
                       {"answer": "Metadata Management", 
                        "correct": True}, 
                       {"answer": "Query Processing", 
                        "correct": False},
                       {"answer": "Database Storage", 
                        "correct": False} ] },
                 { "question": "Which of the following database objects can be cloned in Snowflake?", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "Databases", 
                        "correct": False}, 
                       {"answer": "Schemas", 
                        "correct": False}, 
                       {"answer": "All of the above", 
                        "correct": True}, 
                       {"answer": "Tables", 
                        "correct": False} ] },
                 { "question": "Snowflake is supported on which cloud providers?", 
                   "type": "many_choice", 
                   "answers": [ 
                       {"answer": "GCP", 
                        "correct": True}, 
                       {"answer": "IBM Cloud", 
                        "correct": False}, 
                       {"answer": "AWS", 
                        "correct": True}, 
                       {"answer": "Azure", 
                        "correct": True},
                       {"answer": "Alibaba Cloud", 
                        "correct": False} ] },
                 { "question": "The number of load operations that run in parallel cannot exceed the number of data files to be loaded...", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "False", 
                        "correct": False}, 
                       {"answer": "True", 
                        "correct": True} ] },
                 { "question": "Different editions of snowflake Instances require separate accounts...", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "False", 
                        "correct": False}, 
                       {"answer": "True", 
                        "correct": True} ] }
        ]
        
        if self.num_preguntas > len(quiz):
            raise ValueError("El número de preguntas solicitado es mayor que las disponibles en el cuestionario.")
                
        return sample(quiz, self.num_preguntas)
    






        """
        { "question": "QUESTION?", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "DOWNLOAD", 
                        "correct": False}, 
                       {"answer": "PUT", 
                        "correct": False}, 
                       {"answer": "GET", 
                        "correct": True}, 
                       {"answer": "RETRIEVE", 
                        "correct": False} ] },
        { "question": "QUESTION...", 
                   "type": "multiple_choice", 
                   "answers": [ 
                       {"answer": "False", 
                        "correct": True}, 
                       {"answer": "True", 
                        "correct": False} ] },
        { "question": "QUESTION?", 
                   "type": "many_choice", 
                   "answers": [ 
                       {"answer": "External", 
                        "correct": False}, 
                       {"answer": "Permanent", 
                        "correct": False}, 
                       {"answer": "Secure", 
                        "correct": True}, 
                       {"answer": "Materialized", 
                        "correct": True},
                       {"answer": "Standard", 
                        "correct": True},
                       {"answer": "Transient", 
                        "correct": False} ] },
                        
                        """